cd poly_ch4cl
call run_ch4cl.bat
cd ..\poly_ch4o
call run_ch4o.bat
cd ..\poly_ch4oh
call run_ch4oh.bat
cd ..\poly_ch5
call run_ch5.bat
cd ..\poly_clhbr
call run_clhbr.bat
cd ..\poly_cmc
call run_cmc.bat
cd ..\poly_cwmc
call run_cwmc.bat
cd ..\poly_h2ni
call run_h2ni.bat
cd ..\poly_h3
call run_h3.bat
cd ..\poly_hni
call run_hni.bat
cd ..\poly_ho2
call run_ho2.bat
cd ..\poly_nh3
call run_nh3.bat
cd ..\poly_oh3
call run_oh3.bat
cd ..\poly_ohcl
call run_ohcl.bat